Repository Club-PARD/Zzagaechi_FE, pull requests merged in 2024-12, with the labels that each got.

#3 Feature/detail page 중간 완성 및 앱 로고 올리기
  .gitattributes
  Shortkathon/Shortkathon.xcodeproj/project.pbxproj
  Shortkathon/Shortkathon.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/100.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/102.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/1024.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/108.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/114.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/120.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/128.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/144.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/152.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/16.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/167.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/172.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/180.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/196.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/20.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/216.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/234.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/256.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/258.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/29.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/32.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/40.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/48.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/50.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/512.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/55.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/57.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/58.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/60.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/64.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/66.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/72.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/76.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/80.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/87.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/88.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/92.png
  Shortkathon/Shortkathon/Assets.xcassets/AppIcon.appiconset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/PlusImage.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/PlusImage.imageset/plus-circle.png
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/QuestionImage.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/QuestionImage.imageset/Vector (7).png
  Shortkathon/Shortkathon/Controller/AppleLoginViewController.swift
  Shortkathon/Shortkathon/Controller/DetailPlan/DetailPlanViewController.swift
  Shortkathon/Shortkathon/Controller/DetailPlan/FirstSection/DateCollectionViewCell.swift
  Shortkathon/Shortkathon/Controller/DetailPlan/SecondSection/SeperateDayListTableViewCell.swift
  Shortkathon/Shortkathon/Controller/DetailPlan/SecondSection/SeperateDayListView.swift
  Shortkathon/Shortkathon/Controller/DetailPlan/ThirdSection/SeperateTaskView.swift
  Shortkathon/Shortkathon/Controller/DetailPlan/ThirdSection/SeperateTaskViewTableCell.swift
  Shortkathon/Shortkathon/Controller/Main/MainScheduleViewController.swift
  Shortkathon/Shortkathon/SceneDelegate.swift
Labels: Style, Feature

#4 Feature/detail page 세분화 작업 UI 중 textfIeld 기능 구현
  .gitattributes
  Shortkathon/Shortkathon.xcodeproj/project.pbxproj
  Shortkathon/Shortkathon.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/Tips.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/Tips.imageset/Group 2000.png
  Shortkathon/Shortkathon/Controller/DetailPlan/DetailPlanViewController.swift
  Shortkathon/Shortkathon/Controller/DetailPlan/ThirdSection/SeperateTaskView.swift
  Shortkathon/Shortkathon/Controller/DetailPlan/ThirdSection/SeperateTaskViewTableCell.swift
Labels: Style, Feature

#6 [Feat] : 탭바 세팅
  Shortkathon/Shortkathon/Controller/FirstViewController.swift
  Shortkathon/Shortkathon/Controller/SecondViewController.swift
  Shortkathon/Shortkathon/Controller/ThirdViewController.swift
  Shortkathon/Shortkathon/Controller/ViewController.swift
Labels: Style

#7 Feature/tabbar : 탭바 커스텀
  Shortkathon/Shortkathon.xcodeproj/xcshareddata/xcschemes/Shortkathon.xcscheme
  Shortkathon/Shortkathon/Controller/CalendarViewController.swift
  Shortkathon/Shortkathon/Controller/CustomTabBar.swift
  Shortkathon/Shortkathon/Controller/FirstViewController.swift
  Shortkathon/Shortkathon/Controller/MainViewController.swift
  Shortkathon/Shortkathon/Controller/SeparateTaskViewController.swift
  Shortkathon/Shortkathon/Controller/ThirdViewController.swift
  Shortkathon/Shortkathon/Controller/ViewController.swift
Labels: Style

#8 Feature/tabbar
  Shortkathon/Shortkathon/Assets.xcassets/TabBar/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/TabBar/calender.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/TabBar/calender.imageset/Icon.svg
  Shortkathon/Shortkathon/Assets.xcassets/TabBar/home.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/TabBar/home.imageset/Icon (1).svg
  Shortkathon/Shortkathon/Assets.xcassets/TabBar/plus.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/TabBar/plus.imageset/Icon (2).svg
  Shortkathon/Shortkathon/Controller/CalendarViewController.swift
  Shortkathon/Shortkathon/Controller/CustomTabBar.swift
  Shortkathon/Shortkathon/Controller/MainViewController.swift
  Shortkathon/Shortkathon/Controller/SeparateTaskViewController.swift
  Shortkathon/Shortkathon/Controller/ViewController.swift
Labels: Style

#9 [Feat] : Plus 페이지 모달 추가
  Shortkathon/Shortkathon/Assets.xcassets/TaskPlus/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/TaskPlus/Icon.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/TaskPlus/Icon.imageset/Icon-2.png
  Shortkathon/Shortkathon/Controller/SeparateTaskViewController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SeparateTaskViewController1.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/TaskPlusViewController.swift
  Shortkathon/Shortkathon/Controller/ViewController.swift
Labels: Style

#11 Feature/mainpage : 이미지 애니메이션 추가
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/A.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/A.imageset/Layer_1 2.png
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/N1.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/N1.imageset/Layer_1 1.png
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/N2.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/N2.imageset/Group 2055.png
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/O.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/O.imageset/Layer_1-1 1.png
  Shortkathon/Shortkathon/Controller/Main/MainViewController.swift
  Shortkathon/Shortkathon/Controller/MainViewController.swift
Labels: Style

#12 Feature/mainpage : 화면 이동 코드 구현
  Shortkathon/Shortkathon/Assets.xcassets/Task/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Task/Group 2062.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Task/Group 2062.imageset/Group 2062.png
  Shortkathon/Shortkathon/Assets.xcassets/Task/Group 2063.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Task/Group 2063.imageset/Group 2063.png
  Shortkathon/Shortkathon/Assets.xcassets/Task/Group 20fg.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Task/Group 20fg.imageset/Group 2062.png
  Shortkathon/Shortkathon/Assets.xcassets/Task/Icon-3.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Task/Icon-3.imageset/Icon-3.png
  Shortkathon/Shortkathon/Assets.xcassets/Task/Icon.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Task/Icon.imageset/Icon-2.png
  Shortkathon/Shortkathon/Assets.xcassets/Task/progess.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Task/progess.imageset/progess.png
  Shortkathon/Shortkathon/Assets.xcassets/Task/progess2.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Task/progess2.imageset/progess2.png
  Shortkathon/Shortkathon/Assets.xcassets/Task/progess3.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Task/progess3.imageset/progess3.png
  Shortkathon/Shortkathon/Assets.xcassets/Task/progess4.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Task/progess4.imageset/progess4.png
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController1.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController2.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController3.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController4.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SchedulemodalController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SeparateTaskViewController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SimpleScheduleController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/completemodalController.swift
Labels: Style, Feature

#13 Feature/calendar
  Shortkathon/Shortkathon/APIService/URLClass.swift
  Shortkathon/Shortkathon/Assets.xcassets/Calendar/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Calendar/leftButton.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Calendar/leftButton.imageset/leftButton.png
  Shortkathon/Shortkathon/Assets.xcassets/Calendar/rightButton.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Calendar/rightButton.imageset/rightButton.png
  Shortkathon/Shortkathon/Controller/Calendar/AddButtonModalViewController.swift
  Shortkathon/Shortkathon/Controller/Calendar/CalendarViewController.swift
  Shortkathon/Shortkathon/Controller/CalendarViewController.swift
  Shortkathon/Shortkathon/Controller/ViewController.swift
Labels: Style, Feature

#14 Feature/add3 : 세분화 해야하는 일 페이지 3까지 UI 밑 기능 구현 완료
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/a1.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/a1.imageset/a 쵲옹 1.png
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/n1-1.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/n1-1.imageset/n 최치최최종 1.png
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/n2-1.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/n2-1.imageset/n 최치최최종 2.png
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/o1.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/o1.imageset/O쵲옹.png
  Shortkathon/Shortkathon/Assets.xcassets/Task/Icon_right.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/Task/Icon_right.imageset/Icon-2.png
  Shortkathon/Shortkathon/Assets.xcassets/TaskPlus/Icon.imageset/Icon-2.png
  Shortkathon/Shortkathon/Assets.xcassets/TaskPlus/back.imageset/Icon.png
  Shortkathon/Shortkathon/Controller/GradientButtonViewController.swift
  Shortkathon/Shortkathon/Controller/Main/MainViewController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController1.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController2.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController3.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController4.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SchedulemodalController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SeparateTaskViewController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SimpleScheduleController.swift
  Shortkathon/Shortkathon/Controller/View/ContentView.swift
  Shortkathon/Shortkathon/Controller/View/MainTableViewCell.swift
  Shortkathon/Shortkathon/Controller/View/SeperateTaskView.swift
  Shortkathon/Shortkathon/Controller/View/SeperateTaskViewTableCell.swift
Labels: Style, Feature

#15 [Feat] : 메인 페이지 get, 세분화 두 번째 페이지 포스트 구현 및 사랑이 UI 수정사항 합치기
  Shortkathon/Shortkathon/APIService/APIService.swift
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/timer.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/timer.imageset/Icon (1).png
  Shortkathon/Shortkathon/Assets.xcassets/TaskPlus/Contents.json
  Shortkathon/Shortkathon/Controller/AppleLoginViewController.swift
  Shortkathon/Shortkathon/Controller/Date+Extension.swift
  Shortkathon/Shortkathon/Controller/Main/MainViewController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController1.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController2.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController3.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController4.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SchedulemodalController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SeparateTaskViewController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SimpleScheduleController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/completemodalController.swift
  Shortkathon/Shortkathon/Controller/View/Add4_Page/DateCollectionViewCell.swift
  Shortkathon/Shortkathon/Controller/View/MainTableViewCell.swift
  Shortkathon/Shortkathon/Model/DailySchedule.swift
  Shortkathon/Shortkathon/Model/PlanSubRequest.swift
Labels: Style, Feature

#17 메인 페이지 GET , 단순 일정 페이지 POST, 세부 일정 페이지 1 POST, mainTableViewCell 수정
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/noCheckPlan.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/noCheckPlan.imageset/Ellipse 17.png
  Shortkathon/Shortkathon/Controller/Main/MainViewController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SimpleScheduleController.swift
  Shortkathon/Shortkathon/Controller/View/MainTableViewCell.swift
Labels: API, Style, Feature

#18 Page4
  Shortkathon/Shortkathon/APIService/URLClass.swift
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/description.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/HomePage/description.imageset/Group 2075.png
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/clock.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/clock.imageset/Icon (2).png
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/xButton.imageset/Contents.json
  Shortkathon/Shortkathon/Assets.xcassets/SeperateTaskPage/xButton.imageset/Icon (3).png
  Shortkathon/Shortkathon/Controller/Calendar/AddButtonModalViewController.swift
  Shortkathon/Shortkathon/Controller/Calendar/CalendarResponse.swift
  Shortkathon/Shortkathon/Controller/Calendar/CalendarViewController.swift
  Shortkathon/Shortkathon/Controller/Main/MainViewController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController2.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController3.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController4.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/SimpleScheduleController.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/timemodalController1.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/timemodalController2.swift
  Shortkathon/Shortkathon/View/Add4_Page/DateCollectionViewCell.swift
  Shortkathon/Shortkathon/View/Add4_Page/Page4TaskTableViewCell.swift
  Shortkathon/Shortkathon/View/ContentView.swift
  Shortkathon/Shortkathon/View/MainTableViewCell.swift
  Shortkathon/Shortkathon/View/SeperateTaskView.swift
  Shortkathon/Shortkathon/View/SeperateTaskViewTableCell.swift
Labels: API

#19 [Feat] : url 에러 픽스
  Shortkathon/Shortkathon/APIService/URLClass.swift
  Shortkathon/Shortkathon/Controller/TaskPlus/AddDetailScheduleViewController4.swift
Labels: API
